Repository MarcusPFF/Trening-ICE-SEM1, pull requests merged in 2024-12, with the labels that each got.

#2 changes to domainmodel_v1.puml, deleted duplicate ICE.PDF file. And updated metadata.md added to ##GIT
  src/doc/diagram/domainmodel_v1.puml
  src/doc/docs/ICE .pdf
  src/doc/metadata.md
Labels: duplicate, enhancement

#5 Databases
  src/data/Database.db
  src/data/data.db
Labels: documentation

#4 DBConnector class. Added DBConnector data to metadata.md and changed DBConnector class in class_diagram_v2.puml
  src/doc/diagram/class_diagram_v2_frasigselv.puml
  src/doc/metadata.md
  src/main/java/util/DBConnector.java
Labels: documentation, enhancement
